version: "3.5"

services:
  php_fpm:
      build: .
      container_name: laravel_php_fpm
      working_dir: /usr/share/nginx/laravel-base
      networks:
        - laravel-base
      volumes:
          - ./:/usr/share/nginx/laravel-base

  nginx:
      image: nginx:1.15
      container_name: laravel-base_nginx
      working_dir: /usr/share/nginx/laravel-base
      networks:
        - laravel-base
      ports:
          - "8080:80"
      volumes:
          - ./:/usr/share/nginx/laravel-base
          - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
      image: mysql:5.7
      container_name: laravel-base_mysql
      networks:
        - laravel-base
      environment:
        - MYSQL_DATABASE=laravel_base
        - MYSQL_ROOT_PASSWORD=mysql
        - MYSQL_USER=laravel_base
        - MYSQL_PASSWORD=mysql

networks:
  laravel-base:
    driver: bridge