version: "3.5"

services:
  php_fpm:
      build: .
      container_name: api_ingresse_php_fpm
      working_dir: /usr/share/nginx/api_ingresse
      networks:
        - laravel-api
      volumes:
          - ./:/usr/share/nginx/api_ingresse

  nginx:
      image: nginx:1.15
      container_name: api_ingresse_nginx
      working_dir: /usr/share/nginx/api_ingresse
      networks:
        - laravel-api
      ports:
          - "8080:80"
      volumes:
          - ./:/usr/share/nginx/api_ingresse
          - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
      image: mysql:5.7
      container_name: api_ingresse_mysql
      networks:
        - laravel-api
      environment:
        - MYSQL_DATABASE=api_ingresse
        - MYSQL_ROOT_PASSWORD=mysql
        - MYSQL_USER=root
        - MYSQL_PASSWORD=mysql

networks:
  laravel-api:
    driver: bridge